In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("diabetes.csv")

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
df.shape

(768, 9)

In [5]:
X = df.drop(columns = ["Outcome"])
y = df["Outcome"]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2 , random_state = 42, stratify = y)

In [7]:
X_train_bias = np.c_[np.ones(X_train.shape[0]), X_train] 

In [8]:
X_train_bias.shape

(614, 9)

In [9]:
X_test_bias = np.c_[np.ones(X_test.shape[0]), X_test] 

In [10]:
X_test_bias.shape

(154, 9)

In [11]:
y_train = y_train.to_numpy().reshape(-1,1)

In [12]:
y_train.shape

(614, 1)

In [13]:
y_test = y_test.to_numpy().reshape(-1,1)

In [14]:
y_test.shape

(154, 1)

In [15]:
weights_initial = np.random.randn(X_train_bias.shape[1]) * 0.01

In [16]:
weights_initial = weights_initial.reshape(-1,1)

In [17]:
weights_initial.shape

(9, 1)

In [18]:
def sigmoid(Z):
    return 1 / (1 + np.exp(-1 * Z))

In [19]:
def compute_cost(X, y, W):
    Z = np.dot(X, W)
    y_pred = sigmoid(Z)
    cost = -1 * np.mean(y * np.log(y_pred) + (1 - y) * np.log(1- y_pred))
    return cost

In [20]:
def gradient_descent(X, y, W, learning_rate = 0.001, n_steps = 10000, print_cost = True):
    m = X.shape[0]
    for i in range(n_steps):
        Z = np.dot(X, W)
        y_pred = sigmoid(Z)
        gradient = np.dot(X.T , y_pred - y) / m 
        W -= learning_rate * gradient
        
        if print_cost and i % 100 == 0:
            print(f"Cost is {compute_cost(X, y, W)}")
    
    return W

In [21]:
weights_final = gradient_descent(X_train_bias, y_train, weights_initial, learning_rate = 0.0001, n_steps = 1000, print_cost = True)

Cost is 0.6866145776419513
Cost is 0.625178048438498
Cost is 0.6182448966386416
Cost is 0.6164258380854698
Cost is 0.615642470519695
Cost is 0.6151748451595647
Cost is 0.6148466458431155
Cost is 0.6145955280285847
Cost is 0.6143916517076635
Cost is 0.6142182250777255


In [22]:
weights_final

array([[-0.01053496],
       [ 0.04164765],
       [ 0.01317974],
       [-0.0298837 ],
       [-0.0007371 ],
       [ 0.00132393],
       [-0.00377581],
       [-0.00871535],
       [-0.00366282]])

In [23]:
y_pred_probs = sigmoid(np.dot(X_test_bias, weights_final))

In [24]:
y_pred_probs.shape

(154, 1)

In [25]:
y_pred_probs[:5]

array([[0.5526759 ],
       [0.10656995],
       [0.35879854],
       [0.41012701],
       [0.72443932]])

In [26]:
y_preds = (y_pred_probs > 0.5).astype(int)

In [27]:
y_preds[:5]

array([[1],
       [0],
       [0],
       [0],
       [1]])

In [28]:
accuracy = np.mean(y_preds == y_test)

In [29]:
accuracy

np.float64(0.6558441558441559)

In [33]:
weights_initial = np.random.randn(X_train_bias.shape[1]) * 0.01
weights_initial = weights_initial.reshape(-1,1)
y_pred_probs = sigmoid(np.dot(X_test_bias, weights_initial))
y_preds = (y_pred_probs > 0.5).astype(int)
accuracy = np.mean(y_preds == y_test)

In [32]:
accuracy

np.float64(0.36363636363636365)